In [50]:
from sklearn import datasets, svm, metrics
# Standard scientific Python imports
import matplotlib.pyplot as plt
import pandas as pd

#drop name and ticket information
titanicall_df = pd.read_csv("titanic-train.csv")
#Randomize
titanicall_df = titanicall_df.sample(frac=1)
titanic_features_df = titanicall_df.loc[:, ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
titanic_labels_df = titanicall_df.loc[:, ['PassengerId', 'Survived']]

titanicall_df.head(5)
titanic_labels_df.head(5)
print(titanic_features_df.head(5))

#Feature engeneering
titanic_features_df = pd.get_dummies(titanic_features_df, columns=['Pclass', 'Sex', 'Embarked'])
titanic_features_df = titanic_features_df.fillna(-1)
print(titanic_features_df.describe())
print("Number of men %d" % len(titanic_features_df[titanic_features_df.Sex_male > 0]))

n_samples = len(titanic_labels_df)
print(n_samples)
n_sample_offset = int(n_samples * 0.8)
print(n_sample_offset)

titanic_features_df.head(10)
titanic_features_df.values[:n_sample_offset]

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
668       3    male  43.0      0      0   8.0500        S
751       3    male   6.0      0      1  12.4750        S
229       3  female   NaN      3      1  25.4667        S
196       3    male   NaN      0      0   7.7500        Q
559       3  female  36.0      1      0  17.4000        S
              Age       SibSp       Parch        Fare    Pclass_1    Pclass_2  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    23.600640    0.523008    0.381594   32.204208    0.242424    0.206510
std     17.867496    1.102743    0.806057   49.693429    0.428790    0.405028
min     -1.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      6.000000    0.000000    0.000000    7.910400    0.000000    0.000000
50%     24.000000    0.000000    0.000000   14.454200    0.000000    0.000000
75%     35.000000    1.000000    0.000000   31.000000    0.000000    0.000000
max     80.000000    8.000000    6.000000  512.329200    1.000000    1.000000

         Pclass_3  Sex_female    Sex_male  Embarked_C  Embarked_Q  Embarked_S
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.551066    0.352413    0.647587    0.188552    0.086420    0.722783
std      0.497665    0.477990    0.477990    0.391372    0.281141    0.447876
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
50%      1.000000    0.000000    1.000000    0.000000    0.000000    1.000000
75%      1.000000    1.000000    1.000000    0.000000    0.000000    1.000000
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
Number of men 577
891
712

array([[ 43.,   0.,   0., ...,   0.,   0.,   1.],
       [  6.,   0.,   1., ...,   0.,   0.,   1.],
       [ -1.,   3.,   1., ...,   0.,   0.,   1.],
       ...,
       [ 49.,   1.,   0., ...,   1.,   0.,   0.],
       [ 21.,   2.,   2., ...,   1.,   0.,   0.],
       [ 51.,   0.,   0., ...,   0.,   0.,   1.]])

In [31]:
# Ca marche pas.
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
#titanic_labels_df.to_dict
vec.fit_transform(titanicdata.to_dict).toarray()

TypeError: 'instancemethod' object is not iterable

In [6]:
labels = titanic_labels_df.Survived.values
labels[:5]

array([1, 1, 0, 0, 0])

In [28]:
# Create a classifier: a support vector classifier
classifier = svm.SVC(gamma=0.001)
# We learn the digits on the first 80%
classifier.fit(titanic_features_df.values[:n_sample_offset], titanic_labels_df.Survived.values[:n_sample_offset])

# Now predict the value on the last 20%
expected = titanic_labels_df.Survived[n_sample_offset:]
predicted = classifier.predict(titanic_features_df[n_sample_offset:])

print("Classification report for classifier %s:\n%s\nAccuracy: %s\n"
      % (classifier, metrics.classification_report(expected, predicted), metrics.accuracy_score(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.71      0.95      0.81       116
          1       0.75      0.29      0.41        63

avg / total       0.72      0.72      0.67       179

Accuracy: 0.715083798883

Confusion matrix:
[[110   6]
 [ 45  18]]

In [32]:
from sklearn import linear_model
classifier = linear_model.LogisticRegression(verbose=1, C=10, tol=1e-8)
# We learn the digits on the first 80%
classifier.fit(titanic_features_df.values[:n_sample_offset], titanic_labels_df.Survived.values[:n_sample_offset])

# Now predict the value on the last 20%
expected = titanic_labels_df.Survived[n_sample_offset:]
predicted = classifier.predict(titanic_features_df[n_sample_offset:])

print("Classification report for classifier %s:\n%s\nAccuracy: %s\n"
      % (classifier, metrics.classification_report(expected, predicted), metrics.accuracy_score(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

[LibLinear]Classification report for classifier LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=1e-08,
          verbose=1, warm_start=False):
             precision    recall  f1-score   support

          0       0.82      0.91      0.86       116
          1       0.80      0.62      0.70        63

avg / total       0.81      0.81      0.80       179

Accuracy: 0.810055865922

Confusion matrix:
[[106  10]
 [ 24  39]]

In [44]:
#Appliquer le modèle au données de test.
#drop name and ticket information
from pandas.core.frame import DataFrame

titanictest_df = pd.read_csv("titanic-test.csv")
titanictest_features_df = titanictest_df.loc[:, ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
titanictest_labels_df = titanictest_df.loc[:, ['PassengerId']]

print(titanictest_features_df.head(5))

#Feature engeneering
titanictest_features_df = pd.get_dummies(titanictest_features_df, columns=['Pclass', 'Sex', 'Embarked'])
titanictest_features_df = titanictest_features_df.fillna(-1)

n_samples = len(titanictest_features_df)
print(n_samples)

titanictest_features_df.head(10)

#Appliquons le modèle
predicted = classifier.predict(titanictest_features_df)
print("Size %s, %s" % (len(titanictest_labels_df.PassengerId.values), len(predicted)))


result_df = pd.DataFrame({'PassengerId':titanictest_labels_df.PassengerId.values, 'Survived':predicted})
#Save to disk
result_df.to_csv('titanic-result.csv', index=False)

result_df

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S
418
Size 418, 418

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>PassengerId</th>
      <th>Survived</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>892</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>893</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>894</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>895</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>896</td>
      <td>1</td>
    </tr>
    <tr>
      <th>5</th>
      <td>897</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>898</td>
      <td>1</td>
    </tr>
    <tr>
      <th>7</th>
      <td>899</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>900</td>
      <td>1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>901</td>
      <td>0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>902</td>
      <td>0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>903</td>
      <td>0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>904</td>
      <td>1</td>
    </tr>
    <tr>
      <th>13</th>
      <td>905</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>906</td>
      <td>1</td>
    </tr>
    <tr>
      <th>15</th>
      <td>907</td>
      <td>1</td>
    </tr>
    <tr>
      <th>16</th>
      <td>908</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>909</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>910</td>
      <td>1</td>
    </tr>
    <tr>
      <th>19</th>
      <td>911</td>
      <td>1</td>
    </tr>
    <tr>
      <th>20</th>
      <td>912</td>
      <td>0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>913</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>914</td>
      <td>1</td>
    </tr>
    <tr>
      <th>23</th>
      <td>915</td>
      <td>1</td>
    </tr>
    <tr>
      <th>24</th>
      <td>916</td>
      <td>1</td>
    </tr>
    <tr>
      <th>25</th>
      <td>917</td>
      <td>0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>918</td>
      <td>1</td>
    </tr>
    <tr>
      <th>27</th>
      <td>919</td>
      <td>0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>920</td>
      <td>0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>921</td>
      <td>0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>388</th>
      <td>1280</td>
      <td>0</td>
    </tr>
    <tr>
      <th>389</th>
      <td>1281</td>
      <td>0</td>
    </tr>
    <tr>
      <th>390</th>
      <td>1282</td>
      <td>0</td>
    </tr>
    <tr>
      <th>391</th>
      <td>1283</td>
      <td>1</td>
    </tr>
    <tr>
      <th>392</th>
      <td>1284</td>
      <td>0</td>
    </tr>
    <tr>
      <th>393</th>
      <td>1285</td>
      <td>0</td>
    </tr>
    <tr>
      <th>394</th>
      <td>1286</td>
      <td>0</td>
    </tr>
    <tr>
      <th>395</th>
      <td>1287</td>
      <td>1</td>
    </tr>
    <tr>
      <th>396</th>
      <td>1288</td>
      <td>0</td>
    </tr>
    <tr>
      <th>397</th>
      <td>1289</td>
      <td>1</td>
    </tr>
    <tr>
      <th>398</th>
      <td>1290</td>
      <td>0</td>
    </tr>
    <tr>
      <th>399</th>
      <td>1291</td>
      <td>0</td>
    </tr>
    <tr>
      <th>400</th>
      <td>1292</td>
      <td>1</td>
    </tr>
    <tr>
      <th>401</th>
      <td>1293</td>
      <td>0</td>
    </tr>
    <tr>
      <th>402</th>
      <td>1294</td>
      <td>1</td>
    </tr>
    <tr>
      <th>403</th>
      <td>1295</td>
      <td>0</td>
    </tr>
    <tr>
      <th>404</th>
      <td>1296</td>
      <td>0</td>
    </tr>
    <tr>
      <th>405</th>
      <td>1297</td>
      <td>0</td>
    </tr>
    <tr>
      <th>406</th>
      <td>1298</td>
      <td>0</td>
    </tr>
    <tr>
      <th>407</th>
      <td>1299</td>
      <td>0</td>
    </tr>
    <tr>
      <th>408</th>
      <td>1300</td>
      <td>1</td>
    </tr>
    <tr>
      <th>409</th>
      <td>1301</td>
      <td>1</td>
    </tr>
    <tr>
      <th>410</th>
      <td>1302</td>
      <td>1</td>
    </tr>
    <tr>
      <th>411</th>
      <td>1303</td>
      <td>1</td>
    </tr>
    <tr>
      <th>412</th>
      <td>1304</td>
      <td>1</td>
    </tr>
    <tr>
      <th>413</th>
      <td>1305</td>
      <td>0</td>
    </tr>
    <tr>
      <th>414</th>
      <td>1306</td>
      <td>1</td>
    </tr>
    <tr>
      <th>415</th>
      <td>1307</td>
      <td>0</td>
    </tr>
    <tr>
      <th>416</th>
      <td>1308</td>
      <td>0</td>
    </tr>
    <tr>
      <th>417</th>
      <td>1309</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>418 rows × 2 columns</p>
</div>